title: NU / on the grid
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9983888
  brandStrength: 0.3635285068303347
  lightness: 0.3055854
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  rhythmicContrast: 0.2405762
typography_spectrum: 0.3141783
description: Creatief nieuws uit Zwolle
navigation:
  - name: Updating LA's Historic Hollywood Roosevelt Hotel
    id: 059ffbd7-8913-476b-b43c-9c6695be758b
    type: content
layout_spectrum: 0.8400966781191528
name: NU / reclame
